CREATE TABLE COMPANY_DETAILS(COMID INT NOT NULL PRIMARY KEY ,COMNAME VARCHAR(30),ADDRESS VARCHAR(40));
CREATE TABLE INVOICE(COMID INT REFERENCES COMPANY_DETAILS  NOT NULL,INVNO INT PRIMARY KEY NOT NULL ,INVDATE VARCHAR(20),SERIAL NUMBER(5),LOCATION CHAR(20),CHALANNO NUMBER(5));
SELECT * FROM COMPANY_DETAILS ;
CREATE TABLE INV_DETAILS(INVNO INT REFERENCES INVOICE NOT NULL,DETID INT PRIMARY KEY NOT NULL ,PARTICULARS VARCHAR(30),QUANTITY NUMBER(3),RATE NUMBER(10),AMOUNT VARCHAR(10));
DROP TABLE INV_DETAILS;
DROP TABLE INVOICE;
DROP TABLE COMPANY_DETAILS;
select * from company_details;
select * from INVOICE;
select * from INV_DETAILS;
delete from company_details where comid=1;
delete from INVOICE where comid=1;
commit;
SELECT DETID,PARTICULARS,QUANTITY,RATE,AMOUNT FROM INV_DETAILS;

ALTER TABLE UREG ADD USERPRIVILLAGE CHAR(4) ;

SELECT * FROM UREG;
SELECT COUNT(*) FROM UREG where USERNAME='admin'AND UPASS='123'; 

update ureg set userprivillage='YES' where username='admin';

update ureg set userprivillage='NO' WHERE Userid= (13);
COMMIT;
SELECT COMID,COMNAME FROM COMPANY_DETAILS;
SELECT INVNO,DETID FROM INV_DETAILS WHERE INVNO=2
commit;

SELECT COMPANY_DETAILS.COMID,INVNO,COMNAME,ADDRESS,INVDATE,SERIAL,LOCATION,CHALANNO FROM COMPANY_DETAILS INNER JOIN   INVOICE ON INVOICE.COMID=COMPANY_DETAILS.COMID WHERE COMPANY_DETAILS.COMID =1 AND INVOICE.INVNO=3;
Select COMPANY_DETAILS.COMID,INVNO,COMNAME,ADDRESS,INVDATE,SERIAL,LOCATION,CHALANNO FROM COMPANY_DETAILS INNER JOIN INVOICE On INVOICE.COMID=COMPANY_DETAILS.COMID WHERE COMPANY_DETAILS.COMID ='cibi' AND INVOICE.INVNO=5;

SELECT DETID,PARTICULARS,QUANTITY,RATE,AMOUNT FROM INV_DETAILS WHERE INVNO=5;
SELECT * FROM CUST_DETAILS ORDER BY CID

DELETE FROM INV_DETAILS WHERE DETID=1
DELETE  FROM INV_DETAILS
commit;
DELETE FROM COMPANY_DETAILS WHERE COMID =3
INSERT INTO COMPANY_DETAILS VALUES(2,'VISHNU SOLUTIONS PRIVATE LIMITED','28, GANDHI STREET, ERODE')